INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AcadeMedia', 'ACAD', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Actic Group', 'ATIC', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Autoliv SDB', 'ALIV SDB', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Besqab', 'BESQ', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Betsson B', 'BETS B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('BHG Group', 'BHG', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Bilia A', 'BILI A', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Björn Borg', 'BORG', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Bonava A', 'BONAV A', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Bonava B', 'BONAV B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Boozt', 'BOOZT', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Bulten', 'BULTEN', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Byggmax Group', 'BMAX', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Catena Media', 'CTM', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Clas Ohlson B', 'CLAS B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Dometic Group', 'DOM', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Dustin Group', 'DUST', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Electrolux A', 'ELUX A', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Electrolux B', 'ELUX B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Elon', 'ELON', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Embracer Group B', 'EMBRAC B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Eniro Group', 'ENRO', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Evolution', 'EVO', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Fenix Outdoor International B', 'FOI B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('G5 Entertainment', 'G5EN', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Gaming Innovation Group', 'GIGSEK', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Gränges', 'GRNG', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Hennes & Mauritz B', 'HM B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Husqvarna A', 'HUSQ A', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Husqvarna B', 'HUSQ B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('KABE Group B', 'KABE B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Karnov Group', 'KAR', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Kindred Group', 'KIND SDB', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Lammhults Design Group B', 'LAMM B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('MEKO', 'MEKO', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Mips', 'MIPS', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Modern Times Group A', 'MTG A', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Modern Times Group B', 'MTG B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Moment Group', 'MOMENT', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Nelly Group', 'NELLY', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('New Wave B', 'NEWA B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Nilörngruppen B', 'NIL B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Nobia', 'NOBI', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Pierce Group', 'PIERCE', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Rizzo Group B', 'RIZZO B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Rusta', 'RUSTA', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('RVRC Holding', 'RVRC', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SAS', 'SAS', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Scandic Hotels Group', 'SHOT', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SkiStar B', 'SKIS B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Starbreeze A', 'STAR A', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Starbreeze B', 'STAR B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Stillfront Group', 'SF', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Strax', 'STRAX', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Synsam', 'SYNSAM', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Thule Group', 'THULE', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('VBG GROUP B', 'VBG B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Vestum', 'VESTUM', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('Volvo Car B', 'VOLCAR B', 'Nasdaq Stockholm', 'SEK', 'Consumer Discretionary');
