INSERT INTO financial.symbol (name, ticker, listed_id)
	VALUES
        ('4C Group', '4C', 7),
        ('AAC Clyde Space', 'AAC', 7),
        ('Acarix', 'ACARIX', 7),
        ('Acarix AB TO3', 'ACARIX TO3', 7),
        ('Acast', 'ACAST', 7),
        ('ACROUD', 'ACROUD', 7),
        ('ADDvise Group A', 'ADDV A', 7),
        ('ADDvise Group B', 'ADDV B', 7),
        ('Advenica AB', 'ADVE', 7),
        ('Ages Industri B', 'AGES B', 7),
        ('Arlandastad Group', 'AGROUP', 7),
        ('AlzeCure Pharma', 'ALZCUR', 7),
        ('Auriant Mining', 'AUR', 7),
        ('Avensia', 'AVEN', 7),
        ('Biovica International B', 'BIOVIC B', 7),
        ('Biovica International AB TO 3 B', 'BIOVIC TO 3 B', 7),
        ('Bokusgruppen', 'BOKUS', 7),
        ('ByggPartner Gruppen', 'BYGGP', 7),
        ('CAG Group', 'CAG', 7),
        ('Cheffelo', 'CHEF', 7),
        ('Climeon B', 'CLIME B', 7),
        ('Climeon AB TO 1 B', 'CLIME TO 1 B', 7),
        ('CombinedX', 'CX', 7),
        ('DevPort B', 'DEVP B', 7),
        ('DistIT', 'DIST', 7),
        ('Drillcon', 'DRIL', 7),
        ('Devyser Diagnostics', 'DVYSR', 7),
        ('Ecoclime Group B', 'ECC B', 7),
        ('Embellence Group', 'EMBELL', 7),
        ('Fortinova Fastigheter ser. B', 'FNOVA B', 7),
        ('Fractal Gaming Group', 'FRACTL', 7),
        ('Freja eID Group', 'FREJA', 7),
        ('GomSpace Group', 'GOMX', 7),
        ('Hexicon', 'HEXI', 7),
        ('Implantica SDB', 'IMP A SDB', 7),
        ('Jetpak Top Holding', 'JETPAK', 7),
        ('Kancera', 'KAN', 7),
        ('Lyko Group A', 'LYKO A', 7),
        ('MGI - Media and Games Invest', 'M8G', 7),
        ('MAG Interactive', 'MAGI', 7),
        ('Midsummer', 'MIDS', 7),
        ('Mentice', 'MNTC', 7),
        ('Nanoform Finland Oyj', 'NANOFS', 7),
        ('Navigo Invest Pref', 'NAVIGO PREF', 7),
        ('Navigo Invest', 'NAVIGO STAM', 7),
        ('Neobo Fastigheter', 'NEOBO', 7),
        ('Nexam Chemical Holding', 'NEXAM', 7),
        ('Oneflow', 'ONEF', 7),
        ('Paradox Interactive', 'PDX', 7),
        ('Precio Fishbone B', 'PRCO B', 7),
        ('Physitrack', 'PTRK', 7),
        ('QleanAir', 'QAIR', 7),
        ('Raketech Group Holding', 'RAKE', 7),
        ('RugVista Group', 'RUG', 7),
        ('SaltX Technology Holding B', 'SALT B', 7),
        ('Stenhus Fastigheter i Norden', 'SFAST', 7),
        ('SpectraCure', 'SPEC', 7),
        ('Speqta', 'SPEQT', 7),
        ('Sprint Bioscience', 'SPRINT', 7),
        ('Studentbostäder i Norden', 'STUDBO', 7),
        ('TagMaster B', 'TAGM B', 7),
        ('Terranet B', 'TERRNT B', 7),
        ('Terranet AB TO7 B', 'TERRNT TO7 B', 7),
        ('Terranet AB TO8 B', 'TERRNT TO8 B', 7),
        ('Thunderful Group', 'THUNDR', 7),
        ('Tempest Security', 'TSEC', 7),
        ('Viva Wine Group', 'VIVA', 7),
        ('Zinzino B', 'ZZ B', 7),
        ('2cureX', '2CUREX', 7),
        ('Absolent Air Care Group', 'ABSO', 7),
        ('Acconeer', 'ACCON', 7),
        ('AcouSort', 'ACOU', 7),
        ('AcouSort AB TO2', 'ACOU TO2', 7),
        ('Acuvi', 'ACUVI', 7),
        ('Adtraction Group', 'ADTR', 7),
        ('Adventure Box Technology', 'ADVBOX', 7),
        ('AFRICA ENERGY CORP.', 'AEC', 7),
        ('AegirBio', 'AEGIR', 7),
        ('Svenska Aerogel Holding', 'AERO', 7),
        ('Agtira B', 'AGTIRA B', 7),
        ('Agtira AB TO 1', 'AGTIRA TO 1', 7),
        ('Aino Health', 'AINO', 7),
        ('Byggmästare A J Ahlström H', 'AJA B', 7),
        ('eEducation Albert', 'ALBERT', 7),
        ('Alcadon Group', 'ALCA', 7),
        ('ALM Equity', 'ALM', 7),
        ('ALM Equity Pref', 'ALM PREF', 7),
        ('Alpcot Holding B', 'ALPCOT B', 7),
        ('Alzinova', 'ALZ', 7),
        ('AlzeCure Pharma AB BTA', 'ALZCUR BTA', 7),
        ('Amniotics', 'AMNI', 7),
        ('Annexin Pharmaceuticals', 'ANNX', 7),
        ('Annexin Pharmaceuticals AB BTA', 'ANNX BTA', 7),
        ('Aprendere Skolor', 'APRNDR', 7),
        ('Appspotr', 'APTR', 7),
        ('Arcario', 'ARCA', 7),
        ('Arcoma', 'ARCOMA', 7),
        ('Arctic Minerals', 'ARCT', 7),
        ('Arctic Blue Beverages', 'ARCTIC', 7),
        ('AroCell', 'AROC', 7),
        ('Artificial Solutions Intern.', 'ASAI', 7),
        ('Asarina Pharma', 'ASAP', 7),
        ('Athanase Innovation', 'ATIN', 7),
        ('Avtech Sweden B', 'AVT B', 7),
        ('Awardit', 'AWRD', 7),
        ('aXichem A', 'AXIC A', 7),
        ('aXichem AB TO1A', 'AXIC TO1A', 7),
        ('Axolot Solutions Holding', 'AXOLOT', 7),
        ('Ayima Group B', 'AYIMA B', 7),
        ('Bahnhof B', 'BAHN B', 7),
        ('Bawat Water Technologies', 'BAWAT', 7),
        ('New Bubbleroom Sweden', 'BBROOM', 7),
        ('BeammWave B', 'BEAMMW B', 7),
        ('Beammwave AB BTU', 'BEAMMW BTU', 7),
        ('Besqab', 'BESQAB', 7),
        ('Besqab Pref B', 'BESQAB PREF B', 7),
        ('BIMobject', 'BIM', 7),
        ('Binero Group', 'BINERO', 7),
        ('Bioextrax', 'BIOEX', 7),
        ('Biosergen', 'BIOSGN', 7),
        ('Biosergen AB TO3', 'BIOSGN TO3', 7),
        ('Bio Vitos Pharma', 'BIOVIT', 7),
        ('Bio-Works Technologies', 'BIOWKS', 7),
        ('Nimbus Group', 'BOAT', 7),
        ('BoMill', 'BOMILL', 7),
        ('BoMill AB BTA', 'BOMILL BTA', 7),
        ('Bonäsudden Holding', 'BONAS', 7),
        ('Bonzun', 'BONZUN', 7),
        ('Botnia Exploration Holding', 'BOTX', 7),
        ('BrainCool', 'BRAIN', 7),
        ('BrainCool AB BTA', 'BRAIN BTA', 7),
        ('Bredband2 i Skandinavien', 'BRE2', 7),
        ('Brilliant Future', 'BRILL', 7),
        ('Bambuser', 'BUSER', 7),
        ('Sweden BuyersClub', 'BUY', 7),
        ('Sweden BuyersClub AB BTA', 'BUY BTA', 7),
        ('Candles Scandinavia B', 'CANDLE B', 7),
        ('Careium', 'CARE', 7),
        ('Case Group', 'CASE', 7),
        ('CodeMill', 'CDMIL', 7),
        ('CDON', 'CDON', 7),
        ('Cortus Energy', 'CE', 7),
        ('Cedergrenska', 'CEDER', 7),
        ('Crunchfish', 'CFISH', 7),
        ('ChargePanel', 'CHARGE', 7),
        ('ChargePanel AB TO 1', 'CHARGE TO 1', 7),
        ('ChargePanel AB TO 2', 'CHARGE TO 2', 7),
        ('Checkin.com Group', 'CHECK', 7),
        ('ChromoGenics', 'CHRO', 7),
        ('Cell Impact', 'CI', 7),
        ('Cell Impact AB TO 2', 'CI TO 2', 7),
        ('Cinis Fertilizer', 'CINIS', 7),
        ('CirChem', 'CIRCHE', 7),
        ('Clean Industry Solutions Hold', 'CISH', 7),
        ('Clavister Holding', 'CLAV', 7),
        ('Clavister Holding AB TO 8', 'CLAV TO 8', 7),
        ('Clavister Holding AB TO 9', 'CLAV TO 9', 7),
        ('Corline Biomedical', 'CLBIO', 7),
        ('Clemondo Group', 'CLEM', 7),
        ('Clean Motion', 'CLEMO', 7),
        ('Cline Scientific B', 'CLINE B', 7),
        ('Clinical Laserthermia Syst. B', 'CLS B', 7),
        ('Chordate Medical Holding', 'CMH', 7),
        ('Chordate Medical Holding AB TO 8', 'CMH TO 8', 7),
        ('Scandinavian ChemoTech B', 'CMOTEC B', 7),
        ('Combigene', 'COMBI', 7),
        ('Compodium International', 'COMPDM', 7),
        ('Cereno Scientific B', 'CRNO B', 7),
        ('Cyxone', 'CYXO', 7),
        ('Dala Energi', 'DE', 7),
        ('Duearity', 'DEAR', 7),
        ('Duearity AB TO1', 'DEAR TO1', 7),
        ('Diagonal Bio', 'DIABIO', 7),
        ('Diagonal Bio AB TO1', 'DIABIO TO1', 7),
        ('Diadrom Holding', 'DIAH', 7),
        ('Dignitana', 'DIGN', 7),
        ('Divio Technologies B', 'DIVIO B', 7),
        ('Dlaboratory Sweden', 'DLAB', 7),
        ('Diamyd Medical B', 'DMYD B', 7),
        ('Diamyd Medical AB TO 3 B', 'DMYD TO 3 B', 7),
        ('Diamyd Medical AB TO 4 B', 'DMYD TO 4 B', 7),
        ('Doxa', 'DOXA', 7),
        ('Desenio Group', 'DSNO', 7),
        ('Effnetplattformen Holding', 'EFFH', 7),
        ('Enad Global 7', 'EG7', 7),
        ('Ekobot', 'EKOBOT', 7),
        ('Elicera Therapeutics', 'ELIC', 7),
        ('Elicera Therapeutics AB TO2', 'ELIC TO2', 7),
        ('ELLWEE', 'ELLWEE', 7),
        ('Ellen', 'ELN', 7),
        ('Enersize', 'ENERS', 7),
        ('Enersize Oyj BTU', 'ENERS BTU', 7),
        ('Enzymatica', 'ENZY', 7),
        ('Enorama Pharma', 'ERMA', 7),
        ('ES Energy Save Holding B', 'ESGR B', 7),
        ('Euroafrica Digital Ventures', 'EURA', 7),
        ('ExpreS2ion Biotech Holding', 'EXPRS2', 7),
        ('Exsitec Holding', 'EXS', 7),
        ('Fantasma Games', 'FAGA', 7),
        ('Ferroamp', 'FERRO', 7),
        ('Filo', 'FIL', 7),
        ('Firefly', 'FIRE', 7),
        ('First Venture Sweden B', 'FIRST B', 7),
        ('Flat Capital B', 'FLAT B', 7),
        ('Flexion Mobile', 'FLEXM', 7),
        ('FlexQube', 'FLEXQ', 7),
        ('Flowscape Technology', 'FLOWS', 7),
        ('Fluicell', 'FLUI', 7),
        ('Fluicell AB TO6', 'FLUI TO6', 7),
        ('FluoGuide', 'FLUO', 7),
        ('Footway Group B', 'FOOT B', 7),
        ('Footway Group Pref', 'FOOT PREF', 7),
        ('Fragbite Group', 'FRAG', 7),
        ('Fram Skandinavien B', 'FRAM B', 7),
        ('Freemelt Holding', 'FREEM', 7),
        ('FSport', 'FSPORT', 7),
        ('Gabather', 'GABA', 7),
        ('Gapwaves B', 'GAPW B', 7),
        ('Goodbye Kansas Group', 'GBK', 7),
        ('Gaming Corps', 'GCOR', 7),
        ('Generic Sweden', 'GENI', 7),
        ('Genovis', 'GENO', 7),
        ('Guideline Geo', 'GGEO', 7),
        ('Godsinlösen Nordic', 'GIAB', 7),
        ('Gigasun', 'GIGA', 7),
        ('Gotlandsbolaget A', 'GOTL A', 7),
        ('Gotlandsbolaget B', 'GOTL B', 7),
        ('Gasporox', 'GPX', 7),
        ('Greater Than', 'GREAT', 7),
        ('Guard Therapeutics Intl.', 'GUARD', 7),
        ('Haypp Group', 'HAYPP', 7),
        ('H&D Wireless Sweden Holding B', 'HDW B', 7),
        ('H&D Wireless Holding AB TO4 B', 'HDW TO4 B', 7),
        ('Scandinavian Real Heart', 'HEART', 7),
        ('Scandinavian Real Heart AB TO2', 'HEART TO2', 7),
        ('Hedera Group', 'HEGR', 7),
        ('Heimstaden Pref', 'HEIM PREF', 7),
        ('Heliospectra', 'HELIO', 7),
        ('Hifab Group B', 'HIFA B', 7),
        ('High Coast Distillery B', 'HIGHCO B', 7),
        ('Hilbert Group ser. B', 'HILB B', 7),
        ('Hilbert Group AB TO1 B', 'HILB TO1', 7),
        ('First Hotels', 'HOTEL', 7),
        ('Hoylu', 'HOYLU', 7),
        ('Humble Group', 'HUMBLE', 7),
        ('Iconovo', 'ICO', 7),
        ('Idun Industrier B', 'IDUN B', 7),
        ('Impact Coatings', 'IMPC', 7),
        ('InCoax Networks', 'INCOAX', 7),
        ('InDex Pharmaceuticals Holding', 'INDEX', 7),
        ('Inission B', 'INISS B', 7),
        ('Initiator Pharma', 'INIT', 7),
        ('Insplorion', 'INSP', 7),
        ('Intellego Technologies', 'INT', 7),
        ('Integrum B', 'INTEG B', 7),
        ('Irisity', 'IRIS', 7),
        ('I-Tech', 'ITECH', 7),
        ('Intervacc', 'IVACC', 7),
        ('iZafe Group B', 'IZAFE B', 7),
        ('JonDeTech Sensors', 'JDT', 7),
        ('JonDeTech Sensors AB TO3', 'JDT TO3', 7),
        ('JLT Mobile Computers', 'JLT', 7),
        ('Job Solution Sweden Holding', 'JOBS', 7),
        ('Kakel Max', 'KAKEL', 7),
        ('Kambi Group Plc', 'KAMBI', 7),
        ('Kallebäck Property Invest', 'KAPIAB', 7),
        ('KebNi B', 'KEBNI B', 7),
        ('Kentima Holding', 'KENH', 7),
        ('Kjell Group', 'KJELL', 7),
        ('Klaria Pharma Holding', 'KLAR', 7),
        ('Klimator', 'KLIMAT', 7),
        ('Kollect on Demand Holding', 'KOLL', 7),
        ('Kontigo Care', 'KONT', 7),
        ('Kopy Goldfields', 'KOPY', 7),
        ('LL Lucky Games', 'LADYLU', 7),
        ('Lifeclean International', 'LCLEAN', 7),
        ('Leading Edge Materials Corp.', 'LEMSE', 7),
        ('Nordic LEVEL Group', 'LEVEL', 7),
        ('Nordic LEVEL Group AB TO5B', 'LEVEL TO5B', 7),
        ('Nordic LEVEL Group AB TO6B', 'LEVEL TO6B', 7),
        ('LIDDS', 'LIDDS', 7),
        ('Link Prop Investment', 'LINKAB', 7),
        ('Lipidor', 'LIPI', 7),
        ('Lipum', 'LIPUM', 7),
        ('Litium', 'LITI', 7),
        ('Lohilo Foods', 'LOHILO', 7),
        ('Loyal Solutions', 'LOYAL', 7),
        ('Lipigon Pharmaceuticals', 'LPGO', 7),
        ('Lipigon Pharmaceuticals AB TO3', 'LPGO TO3', 7),
        ('LumenRadio', 'LUMEN', 7),
        ('Luxbright', 'LXB', 7),
        ('Lyckegård Group', 'LYGRD', 7),
        ('Lyckegard Group AB BTA', 'LYGRD BTA', 7),
        ('Mackmyra Svensk Whisky B', 'MACK B', 7),
        ('Mackmyra Svensk Whiskey AB TO 1 B', 'MACK TO 1 B', 7),
        ('Magle Chemoswed Holding', 'MAGLE', 7),
        ('Mantex', 'MANTEX', 7),
        ('Mantex AB TO7', 'MANTEX TO7', 7),
        ('Mavshack', 'MAV', 7),
        ('Maven Wireless Sweden', 'MAVEN', 7),
        ('Maximum Entertainment B', 'MAXENT B', 7),
        ('Medhelp Care', 'MEDHLP', 7),
        ('Meriaura Group Oyj', 'MERIS', 7),
        ('Metacon', 'META', 7),
        ('Metacon AB TO 1', 'META TO 1', 7),
        ('Minesto', 'MINEST', 7),
        ('Minesto AB TO 4', 'MINEST TO 4', 7),
        ('Misen Energy', 'MISE', 7),
        ('Moberg Pharma AB TO 2', 'MOB TO 2', 7),
        ('M.O.B.A. Network', 'MOBA', 7),
        ('Modelon B', 'MODEL B', 7),
        ('Modus Therapeutics Holding', 'MODTX', 7),
        ('Move About Group', 'MOV', 7),
        ('MTI Investment', 'MTI', 7),
        ('Nordic Asia Investment 1987 B', 'NAIG B', 7),
        ('Nanexa', 'NANEXA', 7),
        ('NanoCap Group B', 'NANOC B', 7),
        ('Northbaze Group', 'NBZ', 7),
        ('NeoDynamics', 'NEOD', 7),
        ('Neola Medical', 'NEOLA', 7),
        ('Nepa', 'NEPA', 7),
        ('Newbury Pharmaceuticals', 'NEWBRY', 7),
        ('Nordic Flanges Group', 'NFGAB', 7),
        ('Northgold', 'NG', 7),
        ('Ngenic', 'NGENIC', 7),
        ('Nicoccino Holding', 'NICO', 7),
        ('Nilsson Special Vehicles', 'NILS', 7),
        ('Nordic Iron Ore', 'NIO', 7),
        ('Nitro Games', 'NITRO', 7),
        ('NetJobs Group', 'NJOB', 7),
        ('New Nordic Healthbrands', 'NNH', 7),
        ('Nosa Plugs', 'NOSA', 7),
        ('Norditek Group', 'NOTEK', 7),
        ('Nordrest Holding', 'NREST', 7),
        ('NextCell Pharma', 'NXTCL', 7),
        ('Svenska Nyttobostäder', 'NYTTO', 7),
        ('Svenska Nyttobostäder Pref', 'NYTTO PREF', 7),
        ('Online Brands Nordic', 'OBAB', 7),
        ('Observit', 'OBSE', 7),
        ('Ogunsen B', 'OGUN B', 7),
        ('OncoZenge', 'ONCOZ', 7),
        ('oodash Group', 'OODA', 7),
        ('Opter', 'OPTER', 7),
        ('OptiCept Technologies', 'OPTI', 7),
        ('OrganoClick', 'ORGC', 7),
        ('Ortoma B', 'ORT B', 7),
        ('OssDsign', 'OSSD', 7),
        ('OXE Marine', 'OXE', 7),
        ('Paxman', 'PAX', 7),
        ('Photocat', 'PCAT', 7),
        ('Precomp Solutions B', 'PCOM B', 7),
        ('Perpetua Medical B', 'PERP B', 7),
        ('PILA PHARMA', 'PILA', 7),
        ('ProstaLund', 'PLUN', 7),
        ('PMD Device Solutions', 'PMDS', 7),
        ('Polyplank', 'POLY', 7),
        ('Polygiene Group', 'POLYG', 7),
        ('Promimic', 'PRO', 7),
        ('Prostatype Genomics', 'PROGEN', 7),
        ('Purefun Group', 'PURE', 7),
        ('Qlucore', 'QCORE', 7),
        ('Qiiwi Games', 'QIIWI', 7),
        ('QLife Holding', 'QLIFE', 7),
        ('QLife Holding AB TO 4', 'QLIFE TO 4', 7),
        ('QLife Holding AB TO 5', 'QLIFE TO 5', 7),
        ('Qlosr Group B', 'QLOSR B', 7),
        ('Quartiers Properties', 'QUART', 7),
        ('Quartiers Properties Pref', 'QUART PREF', 7),
        ('QuiaPEG Pharmaceuticals Hold', 'QUIA', 7),
        ('Readly International', 'READ', 7),
        ('Realfiction Holding', 'REALFI', 7),
        ('Redwood Pharma', 'REDW', 7),
        ('Refine Group', 'REFINE', 7),
        ('Resqunit', 'RESQ', 7),
        ('RightBridge Ventures Group', 'RIGHTB', 7),
        ('RightBridge Ventures Group AB TO2', 'RIGHTB TO2', 7),
        ('RanLOS B', 'RLOS B', 7),
        ('Rolling Optics Holding', 'RO', 7),
        ('Ranplan Group', 'RPLAN', 7),
        ('S2Medical B', 'S2M', 7),
        ('S2Medical AB TO 3B', 'S2M TO 3B', 7),
        ('S2Medical AB TO 4B', 'S2M TO 4B', 7),
        ('Saxlund Group', 'SAXG', 7),
        ('ScandBook Holding', 'SBOK', 7),
        ('Scibase Holding', 'SCIB', 7),
        ('Scandion Oncology', 'SCOL', 7),
        ('Scout Gaming Group', 'SCOUT', 7),
        ('ScandiDos', 'SDOS', 7),
        ('Swedencare', 'SECARE', 7),
        ('SECITS Holding', 'SECI', 7),
        ('SenzaGen', 'SENZA', 7),
        ('Serstech', 'SERT', 7),
        ('Scandinavian Enviro Systems', 'SES', 7),
        ('Smart Eye', 'SEYE', 7),
        ('Safello Group', 'SFL', 7),
        ('Safeture', 'SFTR', 7),
        ('SIBEK', 'SIBEK', 7),
        ('Sileon', 'SILEON', 7),
        ('Simris Group B', 'SIMRIS B', 7),
        ('Skåne-möllan', 'SKMO', 7),
        ('Skolon', 'SKOLON', 7),
        ('SMART VALOR SDB', 'SMART SDB', 7),
        ('ShaMaran Petroleum Corp', 'SNM', 7),
        ('Premium Snacks Nordic', 'SNX', 7),
        ('Söder Sportfiske', 'SODER', 7),
        ('Solnaberg Property', 'SOLNA', 7),
        ('SolTech Energy Sweden', 'SOLT', 7),
        ('Sonetel', 'SONE', 7),
        ('SOZAP', 'SOZAP', 7),
        ('SOZAP AB BTA', 'SOZAP BTA', 7),
        ('SOZAP AB TR', 'SOZAP TR', 7),
        ('Spago Nanomedical', 'SPAGO', 7),
        ('SpectrumOne', 'SPEONE', 7),
        ('Stayble Therapeutics', 'STABL', 7),
        ('Stille', 'STIL', 7),
        ('Storytel B', 'STORY B', 7),
        ('SeaTwirl', 'STW', 7),
        ('Surgical Science Sweden', 'SUS', 7),
        ('TalkPool', 'TALK', 7),
        ('Tangiamo Touch Technology', 'TANGI', 7),
        ('Tellusgruppen', 'TELLUS', 7),
        ('Teqnion', 'TEQ', 7),
        ('Tessin Nordic Holding', 'TESSIN', 7),
        ('TH1NG', 'TH1NG', 7),
        ('Titania Holding B', 'TITA B', 7),
        ('Toleranzia', 'TOL', 7),
        ('Toleranzia AB TO4', 'TOL TO4', 7),
        ('Tourn International', 'TOURN', 7),
        ('Train Alliance Sweden B', 'TRAIN B', 7),
        ('Triboron International B', 'TRIBO B', 7),
        ('Triboron International AB TO 2 B', 'TRIBO TO 2 B', 7),
        ('Twiik', 'TWIIK', 7),
        ('Unibap', 'UNIBAP', 7),
        ('Unibap AB TO 3', 'UNIBAP TO 3', 7),
        ('Upsales Technology', 'UPSALE', 7),
        ('USWE Sports', 'USWE', 7),
        ('Unlimited Travel Group', 'UTG', 7),
        ('Vertiseit B', 'VERT B', 7),
        ('Västra Hamnen Corp. Finance', 'VH', 7),
        ('Vimab Group', 'VIMAB', 7),
        ('Vimian Group', 'VIMIAN', 7),
        ('VO2 Cap Holding', 'VO2', 7),
        ('Veg of Lund', 'VOLAB', 7),
        ('Viking Supply Ships B', 'VSSAB B', 7),
        ('W5 Solutions', 'W5', 7),
        ('Waystream Group', 'WAYS', 7),
        ('Westpay', 'WPAY', 7),
        ('White Pearl Technology Group B', 'WPTG B', 7),
        ('WebRock Ventures', 'WRV', 7),
        ('Wall to Wall Group AB TO1 A', 'WTW TO1 A', 7),
        ('Wall to Wall Group AB TO2 A', 'WTW TO2 A', 7),
        ('Wyld Networks', 'WYLD', 7),
        ('Wyld Networks AB TO5', 'WYLD TO5', 7),
        ('Xbrane Biopharma AB TO 1', 'XBRANE TO 1', 7),
        ('Xintela', 'XINT', 7),
        ('Xintela AB TO3', 'XINT TO3', 7),
        ('XMReality', 'XMR', 7),
        ('XP Chemistries', 'XPC', 7),
        ('XP Chemistries AB TO2', 'XPC TO2', 7),
        ('XP Chemistries AB TO3', 'XPC TO3', 7),
        ('SaveLend Group', 'YIELD', 7),
        ('Yubico', 'YUBICO', 7),
        ('Zaplox', 'ZAPLOX', 7),
        ('Zaplox AB TO3', 'ZAPLOX TO3', 7),
        ('Zazz Energy of Sweden B', 'ZAZZ B', 7),
        ('ZAZZ Energy of Sweden AB BTU B', 'ZAZZ BTU B', 7),
        ('Ziccum', 'ZICC', 7),
        ('Ziccum AB TO5', 'ZICC TO5', 7),
        ('ZignSec', 'ZIGN', 7),
        ('ZignSec AB BTA', 'ZIGN BTA', 7),
        ('ZignSec AB TR', 'ZIGN TR', 7),
        ('Zwipe', 'ZWIPE', 7),
        ('Zwipe AS TO 1', 'ZWIPE TO 1', 7);