INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AKER BP', 'AKRBP', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AKER SOLUTIONS', 'AKSO', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('DNO', 'DNO', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('EQUINOR', 'EQNR', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SEADRILL', 'SDRL', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SUBSEA 7', 'SUBC', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('TGS', 'TGS', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('VÅR ENERGI', 'VAR', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AKASTOR', 'AKAST', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('BLUENORD', 'BNOR', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('BORR DRILLING', 'BORR', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('BW ENERGY LIMITED', 'BWE', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('BW OFFSHORE LTD', 'BWO', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('NORTHERN OCEAN LTD', 'NOL', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('ODFJELL DRILLING', 'ODL', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('OKEA', 'OKEA', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('PANORO ENERGY', 'PEN', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('PGS', 'PGS', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SEACREST PETROLEO', 'SEAPT', 'Euronext Expand Oslo', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SHELF DRILLING', 'SHLF', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SIEM OFFSHORE', 'SIOFF', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SOLSTAD OFFSHORE', 'SOFF', 'Oslo Børs', 'NOK', 'OIL');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('2020 BULKERS', '2020', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AMSC', 'AMSC', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AVANCE GAS HOLDING', 'AGAS', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AWILCO LNG', 'ALNG', 'Euronext Expand Oslo', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('BELSHIPS', 'BELCO', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('BW LPG', 'BWLPG', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('EQVA', 'EQVA', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('FLEX LNG', 'FLNG', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('FRONTLINE', 'FRO', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('GC RIEBER SHIPPING', 'RISH', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('GOLDEN OCEAN GROUP', 'GOGL', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('GRAM CAR CARRIERS', 'GCC', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('HAFNIA LIMITED', 'HAFNI', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('JINHUI SHIPP TRANS', 'JIN', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('KLAVENESS COMBINAT', 'KCC', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('MPC CONTAINER SHIP', 'MPCC', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('ODFJELL SER. A', 'ODF', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('ODFJELL SER. B', 'ODFB', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('OKEANIS ECO TANKER', 'OET', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('PHILLY SHIPYARD', 'PHLY', 'Euronext Expand Oslo', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SAGA PURE', 'SAGA', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('STOLT-NIELSEN', 'SNI', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('WALLENIUS WILHELMS', 'WAWI', 'Oslo Børs', 'NOK', 'SHIPPING');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('MOWI', 'MOWI', 'Oslo Børs', 'NOK', 'SALMON');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SALMAR', 'SALM', 'Oslo Børs', 'NOK', 'SALMON');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('BAKKAFROST', 'BAKKA', 'Oslo Børs', 'NOK', 'SALMON');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('LERØY SEAFOOD GP', 'LSG', 'Oslo Børs', 'NOK', 'SALMON');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AUSTEVOLL SEAFOOD', 'AUSS', 'Oslo Børs', 'NOK', 'SALMON');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('GRIEG SEAFOOD', 'GSF', 'Oslo Børs', 'NOK', 'SALMON');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('SALMON EVOLUTION', 'SALME', 'Oslo Børs', 'NOK', 'SALMON');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('ATLANTIC SAPPHIRE', 'ASA', 'Oslo Børs', 'NOK', 'SALMON');
INSERT INTO symbol (name, ticker, market, currency, industry) VALUES ('AKER BIOMARINE', 'AKBM', 'Oslo Børs', 'NOK', 'SALMON');