security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/FinanceDB
    username: postgres
    password: replace-password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
downloaddata:
  daily-data-script-path: /home/oskar/Dokumenter/simulator/downloadData/fetch_all_tick_daily.sh
  preclose-data-script-path: /home/oskar/Dokumenter/simulator/downloadData/fetch_preclose.sh
  dividends-script-path: /home/oskar/Dokumenter/simulator/downloadData/fetch_dividends.sh
  folder-path: /home/oskar/Dokumenter/simulator/downloadData
